Separated SQL commands to a new file

diff --git a/.github/workflows/smoke-test.yml b/.github/workflows/smoke-test.yml
--- a/.github/workflows/smoke-test.yml
+++ b/.github/workflows/smoke-test.yml
@@ -34,7 +34,7 @@ jobs:
       - name: Install psql
         run: sudo apt install postgresql-client
 
-      - name: Run the smoke test
+      - name: Set up environment and Docker container
         run: |
           set -eu
           export PGHOST=localhost
@@ -43,6 +43,9 @@ jobs:
           docker container stop smoketest-container || true
           docker container rm smoketest-container || true
           docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=${PGPASSWORD} --name smoketest-container smoketest-image
+
+      - name: Check if the container is running
+        run: |
           for _ in {1..120}
           do
             if [ -z "$(docker container ls -q --filter name=smoketest-container)" ]
@@ -50,47 +53,53 @@ jobs:
               echo "Smoketest container is not running"
               exit 1
             fi
-            if psql -c "select 1"
-            then
-              echo "Test Citus Extension"
-              psql -c "CREATE EXTENSION citus;"
-              psql -c "SELECT * FROM citus_version();"
-
-              echo "Test Citus Distributed Table"
-              psql -c "CREATE TABLE test_distributed_table (id serial primary key, data text);"
-              psql -c "SELECT create_distributed_table('test_distributed_table', 'id');"
-              psql -c "INSERT INTO test_distributed_table (data) VALUES ('test data');"
-              psql -c "SELECT * FROM test_distributed_table;"
-
-              echo "Test PostGIS Extension"
-              psql -c "CREATE EXTENSION postgis;" || true
-              psql -c "SELECT PostGIS_Version();"
-
-              echo "Test PostGIS Geometry Function"
-              psql -c "CREATE TABLE test_geometry_table (id serial primary key, geom geometry(Point, 4326));"
-              psql -c "INSERT INTO test_geometry_table (geom) VALUES (ST_GeomFromText('POINT(0 0)', 4326));"
-              psql -c "SELECT * FROM test_geometry_table;"
-
-              echo "Test zombodb Extension"
-              psql -c "CREATE EXTENSION zombodb;"
-              psql -c "SELECT zdb.internal_version();"
-              
-              echo "Test pg_repack Extension"
-              psql -c "CREATE EXTENSION pg_repack;"
-              psql -c "select repack.version(), repack.version_sql();"
-
-              echo "Test pgautofailover Extension"
-              psql -c "CREATE EXTENSION pgautofailover CASCADE;"
-              psql -c "SELECT pgautofailover.formation_settings();"
-              break
-            fi
             sleep 1
           done
-          if ! psql -c "select 1"
-          then
-            echo "Cannot connect to PostgreSQL"
-            exit 1
-          fi
+
+      - name: Run the smoke test
+        run: psql -h localhost -U postgres -d smoke_tests_db -f smoke-test.sql
+
+      #         echo "Test Citus Extension"
+      #         psql -c "CREATE EXTENSION citus;"
+      #         psql -c "SELECT * FROM citus_version();"
+
+      #         echo "Test Citus Distributed Table"
+      #         psql -c "CREATE TABLE test_distributed_table (id serial primary key, data text);"
+      #         psql -c "SELECT create_distributed_table('test_distributed_table', 'id');"
+      #         psql -c "INSERT INTO test_distributed_table (data) VALUES ('test data');"
+      #         psql -c "SELECT * FROM test_distributed_table;"
+
+      #         echo "Test PostGIS Extension"
+      #         psql -c "CREATE EXTENSION postgis;" || true
+      #         psql -c "SELECT PostGIS_Version();"
+
+      #         echo "Test PostGIS Geometry Function"
+      #         psql -c "CREATE TABLE test_geometry_table (id serial primary key, geom geometry(Point, 4326));"
+      #         psql -c "INSERT INTO test_geometry_table (geom) VALUES (ST_GeomFromText('POINT(0 0)', 4326));"
+      #         psql -c "SELECT * FROM test_geometry_table;"
+
+      #         echo "Test zombodb Extension"
+      #         psql -c "CREATE EXTENSION zombodb;"
+      #         psql -c "SELECT zdb.internal_version();"
+              
+      #         echo "Test pg_repack Extension"
+      #         psql -c "CREATE EXTENSION pg_repack;"
+      #         psql -c "select repack.version(), repack.version_sql();"
+
+      #         echo "Test pgautofailover Extension"
+      #         psql -c "CREATE EXTENSION pgautofailover CASCADE;"
+      #         psql -c "SELECT pgautofailover.formation_settings();"
+      #         break
+      #       fi
+      #       sleep 1
+      #     done
+      #     if ! psql -c "select 1"
+      #     then
+      #       echo "Cannot connect to PostgreSQL"
+      #       exit 1
+      #     fi
+
+      # - name: Run the smoke test
 
       - name: Show the logs
         if: always()
